version: '3.8'
networks:
  dex-network:
    driver: "bridge"

services:

  # DEX common data source
  dex-mysql:
    container_name: "dex-datastore"
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - dex-network

  dex-api-gateway:
    image: "dex-services-dex-api-gateway"
    build:
      context: "foundation/dex-api-gateway/."
      dockerfile: "Dockerfile"
    networks:
      - dex-network
    ports:
      - "8080:8080"
    environment:
      EUREKA_URI: "http://dex-discovery-service:8761/eureka"

  dex-discovery-service:
    image: "dex-services-dex-discovery-service"
    build:
      context: "foundation/dex-service-discovery/."
      dockerfile: "Dockerfile"
    networks:
      - dex-network
    ports:
      - "8761:8761"

  # DEX authentication service
  dex-auth-service:
    build:
      context: "services/dex-auth-service/."
      dockerfile: "Dockerfile"
    image: "dex-services-dex-auth-service:latest"
    platform: linux/amd64
    environment:
      EUREKA_URI: "http://dex-discovery-service:8761/eureka"
      DATABASE_INSTANCE: "dex-datastore"
      DATABASE_NAME: "dex_auth_service"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
    ports:
      - "9000:8080"
    networks:
      - dex-network
    depends_on:
      - dex-mysql

  # Dex address service
  dex-address-service:
    build:
      context: "services/dex-address-service/."
      dockerfile: "Dockerfile"
    image: "dex-services-dex-address-service:latest"
    platform: linux/amd64
    environment:
      EUREKA_URI: "http://dex-discovery-service:8761/eureka"
      DATABASE_INSTANCE: "dex-datastore"
      DATABASE_NAME: "dex_address_service"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
    ports:
      - "9001:8080"
    networks:
      - dex-network
    depends_on:
      - dex-mysql

  # Dex exchange service
  dex-exchange-service:
    build:
      context: "services/dex-exchange-service/."
      dockerfile: "Dockerfile"
    image: "dex-services-dex-exchange-service:latest"
    platform: linux/amd64
    environment:
      EUREKA_URI: "http://dex-discovery-service:8761/eureka"
      DATABASE_INSTANCE: "dex-datastore"
      DATABASE_NAME: "dex_exchange_service"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
    ports:
      - "9002:8080"
    networks:
      - dex-network
    depends_on:
      - dex-mysql
