server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: dex-api-gateway-service

  cloud:
    gateway:
      routes:
        - id: dex-address-service
          uri: lb://DEX-ADDRESS-SERVICE
          predicates:
            - Path=/address/**
        - id: dex-auth-service
          uri: lb://DEX-AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: dex-exchange-service
          uri: lb://DEX-EXCHANGE-SERVICE
          predicates:
            - Path=/exchange/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
