server:
  port: 8083
  servlet:
    context-path: "/auth"

spring:
  application:
    name: dex-auth-service
  datasource:
    url: jdbc:mysql://${DATABASE_INSTANCE:localhost}:3306/${DATABASE_NAME:dex_auth}?createDatabaseIfNotExist=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: false


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
