server:
  port: 8082
  servlet:
    context-path: "/exchange"
spring:
  application:
    name: dex-exchange-service
  datasource:
    url: jdbc:mysql://${DATABASE_INSTANCE:localhost}:3306/${DATABASE_NAME:dex_exchange}?createDatabaseIfNotExist=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: false


logging:
  level:
    me:
      sithiramunasinghe:
        services:
          exchangeservice: debug

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
