server:
  port: 8080

spring:
  application:
    name: dex-address-service
  datasource:
    url: jdbc:mysql://${DATABASE_INSTANCE:localhost}:3306/${DATABASE_NAME}?createDatabaseIfNotExist=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: false
